name: Update

on:
  schedule:
    - cron: '13 22 * * *'

jobs:
  latest:
    uses: ./.github/workflows/run.yml

  preview:
    uses: ./.github/workflows/run.yml
    with:
      version: 'preview'
      tag: 'preview'
