name: Update

on:
  schedule:
    - cron: '15 2 * * *'
    - cron: '40 2 * * *'

jobs:
  latest:
    uses: ./.github/workflows/run.yml

  preview:
    uses: ./.github/workflows/run.yml
    with:
      version: 'preview'
      tag: 'preview'
