name: Update

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  latest:
    uses: ./.github/workflows/run.yml
    secrets: inherit

  preview:
    uses: ./.github/workflows/run.yml
    secrets: inherit
    with:
      version: 'preview'
      tag: 'preview'
